### ISSUE TITLE
Question about the CharDataset

### ISSUE THREAD

**Issue by gcoter** [karpathy/minGPT#5]
Hello,

I was having a quick look at the `play_char.ipynb` notebook (great project by the way!) and I have a question regarding these two lines:
```
x = torch.tensor(dix[:-1], dtype=torch.long)
y = torch.tensor(dix[1:], dtype=torch.long)
```

In the README, you say that:
> all that's going on is that a sequence of indices goes into a sequence of transformer blocks, and a probability distribution of the next index comes out

Regarding `x`, I understand that it is a sequence of characters (the last one is not included). Regarding `y`, I understand that it is supposed to be the last character (which is not included in `x`). So I would have expected something like this:
```
y = torch.tensor(dix[-1], dtype=torch.long)
```

I don't understand why you define `y` as a sequence, starting from the second character. Am I wrong?

**Comment by djstrong** [comment]
You are right, but here the model is trained for any length input sequence starting from length of 1 and predicting next character. So, the characters are fed by one and the prediction is made with backward propagation.

**Comment by gcoter** [comment]
Thanks for your response @djstrong :slightly_smiling_face: Ok, so if I understand well, let's say that the base string is "abcd", that means that the model will be trained with:
- "a" -> "b"
- "ab" -> "c"
- "abc" -> "d"

So, starting from one string, we actually make a training step on all the sub-strings at once (they are treated as one training batch), right?

**Comment by djstrong** [comment]
Yes

**Comment by gcoter** [comment]
Ok, thank you very much!

**Comment by karpathy** [comment]
Yep! This is exactly what I meant by "over sequence length" when I say "being clever with batching (both across examples and over sequence length) so that training is efficient." in the readme. We're amortizing the forward pass to the backward pass at each point in the sequence as well, but with a reduced context. This is helpful when the test time prompt is shorter than block size, as an example, because the model is trained to work for variably sized context windows.

**Comment by gcoter** [comment]
Understood, thank you for your explanation :slightly_smiling_face:
